---
name: 01 Azure Landing Zones Continuous Integration

on:
  pull_request:
    branches: [main]
    paths: &ci_modules
      - '01_platform_connectivity/**'
      - '02_platform_management/**'
  workflow_dispatch:
    inputs:
      module:
        description: 'Which module directory to run'
        required: true
        type: choice
        options: *ci_modules
      terraform_cli_version:
        description: 'Terraform CLI Version'
        required: true
        default: 'latest'
        type: string

jobs:
  validate_and_plan_auto:
    if: ${{ github.event_name == 'pull_request' }}
    name: CI • ${{ matrix.module }} (auto)
    strategy:
      fail-fast: false
      matrix:
        module: *ci_modules
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    uses: gregc-dev-01/alz-mgmt/.github/workflows/ci-template.yaml@main
    with:
      root_module_folder_relative_path: ${{ matrix.module }} # template strips '/**'
      terraform_cli_version: ${{ github.event.inputs.terraform_cli_version || 'latest' }}

  validate_and_plan_manual:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    name: CI • ${{ matrix.module }} (manual)
    strategy:
      fail-fast: false
      matrix:
        module: ['${{ github.event.inputs.module }}']
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    uses: gregc-dev-01/alz-mgmt/.github/workflows/ci-template.yaml@main
    with:
      root_module_folder_relative_path: ${{ matrix.module }}
      terraform_cli_version: ${{ github.event.inputs.terraform_cli_version || 'latest' }}
